name: Deploy Policy Bundle

on:
  workflow_dispatch:
  #push:
  #  branches: [develop]
  #  paths:
  #    - 'policies/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EnforceAuth
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Policy Bundle
        uses: EnforceAuth/mono/packages/ci/github-action@main
        with:
          ci-entity-id: '5f8c8d09-75e0-4568-823a-166796b90670'
          target-entity-id: '9191f3aa-6cba-4c1c-8bfb-2c6055cfa36a'
          api-url: 'https://rsh4xw59xa.execute-api.us-east-1.amazonaws.com/dev'
          wait-for-completion: true
          timeout-minutes: 10
